{
 "title": "Relatório  1",
 "description": "Relatório que exibe a duração total de uma playlist",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "playlist", "label": "Playlist", "query": "relatorio_1" },
   {
    "name": "id_playlist",
    "label": "id_playlist",
    "query": "relatorio_1{nome_playlist=\"$playlist\"}"
   },
   {
    "name": "duracao",
    "label": "duracao",
    "query": "sum(relatorio_1{id_playlist=\"$id_playlist\"})"
   }
  ]
 },
 "panels": [
  { "title": "Duração total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dados Relatório",
   "type": "table",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "relatorio_1{id_playlist=\"$id_playlist\"}"
    }
   ]
  },
  {
   "title": "Horas",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "min",
   "targets": [
    {
     "expr": "floor(((sum(relatorio_1{id_playlist=\"$id_playlist\"}) / 1000) / 60) / 60)"
    }
   ]
  },
  {
   "title": "Minutos",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 1 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "floor(((sum(relatorio_1{id_playlist=\"$id_playlist\"}) / 1000) / 60) % 60)"
    }
   ]
  },
  {
   "title": "Segundos",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "min",
   "targets": [
    {
     "expr": "floor((sum(relatorio_1{id_playlist=\"$id_playlist\"}) / 1000)  % 60)"
    }
   ]
  }
 ]
}